"""Generate DATASHEET.md — product-style datasheet for the card.

All pin/connector tables are extracted from the live SKiDL circuit (single
source of truth); specs cite the stored reference datasheets. Prose lives in
the template below. Run: `make datasheet` (or uv run python tools/gen_datasheet.py).
"""

import subprocess
import sys
from datetime import date
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "tools"))
from view_defs import BOT_CALLOUTS, TOP_CALLOUTS  # noqa: E402

# signal -> human function, for the connector tables
J3_FN = {"GND": "Ground", "+3V3": "3.3 V out (card rail)",
         "IO8": "I2C SDA", "IO9": "I2C SCL"}
J4_FN = {"TXD0": "UART0 TX (ROM console)", "RXD0": "UART0 RX",
         "IO10": "GPIO / SPI CS (FSPICS0)", "IO11": "GPIO / SPI MOSI (FSPID)",
         "IO12": "GPIO / SPI CLK (FSPICLK)", "IO13": "GPIO / SPI MISO (FSPIQ)",
         "IO14": "GPIO (FSPIWP)", "IO21": "GPIO (RTC-capable)"}
EDGE_FN = {
    "VCC_3V3": "3.3 V supply in",
    "GND": "Ground",
    "USBH3_D_P": "USB 2.0 D+",
    "USBH3_D_N": "USB 2.0 D−",
    "PERST_n": "Card reset (EN), active-low, diode-isolated",
    "PCIE_1_GPIO_5": "Boot-mode strap (IO0), active-low, diode-isolated",
    "W_DISABLE1_n": "Boot-mode strap (IO0), alternate, diode-isolated",
}


def _connector_table(part, fn_map):
    rows = []
    for pin in sorted(part.pins, key=lambda p: int(p.num)):
        net = pin.nets[0].name if pin.nets else "—"
        sig = net.replace("IO0_BOOT", "IO0")
        rows.append(f"| {pin.num} | {sig} | {fn_map.get(net, '')} |")
    return "\n".join(rows)


def _edge_table(j1):
    rows = []
    for pin in sorted(j1.pins, key=lambda p: int(p.num)):
        if not pin.nets:
            continue
        net = pin.nets[0].name
        base = net.replace("+3V3_M2", "VCC_3V3")
        fn = EDGE_FN.get(pin.name, "")
        rows.append(f"| {pin.num} | {pin.name} | {net} | {fn} |")
    return "\n".join(rows)


def main():
    import design
    design.build()
    import builtins
    circuit = builtins.default_circuit
    parts = {p.ref: p for p in circuit.parts}

    git_rev = subprocess.run(["git", "describe", "--always", "--dirty"],
                             cwd=ROOT, capture_output=True,
                             text=True).stdout.strip() or "dev"

    top_legend = "\n".join(f"| {i} | {t} |" for i, (_r, t)
                            in enumerate(TOP_CALLOUTS, 1))
    bot_legend = "\n".join(f"| {i} | {t} |" for i, (_r, t)
                            in enumerate(BOT_CALLOUTS, 1))
    md = TEMPLATE.format(
        date=date.today().isoformat(), rev=git_rev,
        j3=_connector_table(parts["J3"], J3_FN),
        j4=_connector_table(parts["J4"], J4_FN),
        edge=_edge_table(parts["J1"]),
        top_legend=top_legend, bot_legend=bot_legend,
    )
    out = ROOT / "DATASHEET.md"
    out.write_text(md)
    print("wrote", out)


TEMPLATE = """\
# ESP32 M.2 Companion — Datasheet

**M.2 Key-B 2242 USB companion microcontroller card**
Preliminary · rev `{rev}` · {date} · © 2026 Stefano Viola · CERN-OHL-P v2
*(generated by `make datasheet` — do not edit by hand)*

<p align="center"><img src="docs/img/board_iso.png" width="480"
   alt="3D render"></p>

The card adds a fully host-controlled ESP32-S3 to any embedded Linux system
with an M.2 Key-B socket: it enumerates as a USB CDC device, is flashable and
even brick-recoverable purely from the host, and offloads realtime GPIO /
I2C / SPI / UART work — with Wi-Fi and Bluetooth LE included. Primary host:
Toradex Verdin family (Mallow carrier).

## Features

- **MCU**: ESP32-S3-WROOM-1-N8R2 — Xtensa dual-core 32-bit LX7 @ 240 MHz,
  single-precision FPU, 512 KB SRAM + 16 KB RTC SRAM, 384 KB ROM
- **Memory**: 8 MB quad-SPI flash, 2 MB quad-SPI PSRAM (in module)
- **Radio**: Wi-Fi 4 (802.11b/g/n, 2.4 GHz, up to 150 Mbps, up to
  20.5 dBm TX) · Bluetooth 5 LE + mesh · on-module PCB antenna
- **Host link**: USB 2.0 full-speed on the M.2 edge, native USB-Serial-JTAG
  → CDC console, `esptool` flashing, and JTAG debugging with zero extra parts
- **Host-controlled recovery**: reset (EN) and boot-strap (IO0) on M.2
  sideband pins, Schottky-isolated — a bricked card is reflashed entirely
  from the host, no buttons, no cables
- **IO**: Qwiic/STEMMA-QT I2C port (JST SH-4) + UART/SPI/GPIO port
  (JST SH-8), 3.3 V logic
- **Form factor**: M.2 Key-B 2242 (22 × 42 mm, 0.8 mm PCB, 4-layer),
  single 3.3 V supply from the slot
- **Open source hardware** (CERN-OHL-P v2), schematic-as-code (SKiDL),
  assembled by JLCPCB

## Block diagram

```mermaid
flowchart LR
    subgraph HOST["Linux host (M.2 Key-B slot)"]
        USB["USB 2.0 FS"]
        GPIOs["2x sideband GPIO"]
        PWR["3.3 V"]
    end
    subgraph CARD["esp32-m2-companion"]
        ESD["USBLC6-2 ESD"]
        DIODE["Schottky isolation"]
        FB["Ferrite + bulk"]
        MCU["ESP32-S3-WROOM-1\\n(USB-Serial-JTAG)"]
        LED["2x LED"]
        J3["J3 Qwiic I2C"]
        J4["J4 UART/SPI/GPIO"]
    end
    USB <--> ESD <--> MCU
    GPIOs --> DIODE -->|EN / IO0| MCU
    PWR --> FB --> MCU
    MCU --> LED
    MCU <--> J3
    MCU <--> J4
```

## Specifications

| Parameter | Value | Source |
|---|---|---|
| Supply voltage | 3.3 V ±5 % from M.2 edge (no on-card regulator) | SPEC §6.2 |
| Supply current | ~95 mA Wi-Fi RX · ~355 mA avg TX @ 20.5 dBm (bursts higher) · design budget 500 mA | WROOM DS Table 6-4 |
| Host interface | USB 2.0 full-speed (12 Mbps), CDC-ACM via USB-Serial-JTAG | WROOM DS §Pin Definitions |
| Logic level (IO ports) | 3.3 V (not 5 V tolerant) | ESP32-S3 DS |
| Wi-Fi | 802.11b/g/n 2.4 GHz (2412–2484 MHz), ≤150 Mbps, ≤20.5 dBm | WROOM DS §7.1 |
| Bluetooth | 5 (LE) + mesh, ≤20 dBm | WROOM DS §7.2 |
| Operating temperature | −40 … +85 °C (module limit) | WROOM DS Table 1-1 |
| Dimensions | 22 × 42 mm (M.2 2242), 0.8 mm PCB | M.2 EM spec |
| Height (top) | 4.2 mm max (JST headers; module 3.1 mm) — ≈6.3 mm with SH plug mated | JST eSH catalog |
| Height (bottom) | ≤1.5 mm — within the 2.54 mm B-side allowance of an H4.2 socket | M.2 EM spec Fig 38 |
| ESD (USB lines) | IEC 61000-4-2 level 4 (USBLC6-2SC6) | ST/UMW DS |

> **Height note**: the module (3.1 mm) exceeds the M.2 1.5 mm top-side
> envelope. The card fits open sockets (e.g. Mallow X17, carrier bottom) but
> **not** enclosed hosts (laptops) — see `docs/risks.md` R11.

## M.2 edge interface (used pins)

Only the pins below are electrically used; the full 75-position table with
the standard WWAN mapping is in [`docs/pinmap.md`](docs/pinmap.md).

| Pin | Name (card) | Net | Function |
|---|---|---|---|
{edge}

Sideband inputs are Schottky-isolated with on-card 10 kΩ pull-ups: any host
may **pull them low** (open-drain / drive-low-then-release); a host must not
hold them push-pull high below 2.8 V. Unconnected sidebands = normal boot.

### Recovery sequence (bricked firmware)

```
host: IO0-strap GPIO -> low          # M.2 pin 20 (or pin 8)
host: pulse PERST# low >= 5 ms       # M.2 pin 50
      -> ROM download mode -> esptool.py over the same USB port
host: release both (Hi-Z)            # normal boot
```

On Mallow: PERST# = SODIMM 244 (free it from the PCIe DT node);
pin 20 reaches the SoM via the X16.19 jumper. Details: ADR 0002.

## IO connectors

### J3 — Qwiic / STEMMA-QT I2C (JST SH-4, BM04B-SRSS-TB)

| Pin | Signal | Function |
|---|---|---|
{j3}

Standard Qwiic pinout — off-the-shelf sensor cables plug in directly.
I2C pull-ups are DNP on-card (Qwiic peripherals provide their own);
footprints R5/R6 (10 k) can be fitted if needed.

### J4 — UART / SPI / GPIO (JST SH-8, BM08B-SRSS-TB)

| Pin | Signal | Function |
|---|---|---|
{j4}

Both connectors are vertical (top-entry) 1.0 mm JST SH: plugs mate
perpendicular to the card and can be (un)plugged with the card in the slot.
UART0 doubles as the ROM bootloader console. The SPI set is the native
FSPI IOMUX group (up to 80 MHz).

## Product views

<p align="center"><img src="docs/img/view_top.png" width="620" alt="top view"></p>

| # | Top side |
|---|---|
{top_legend}

<p align="center"><img src="docs/img/view_bottom.png" width="620" alt="bottom view"></p>

| # | Bottom side |
|---|---|
{bot_legend}

## Mechanical data

<p align="center"><img src="docs/img/mechanical.png" width="560" alt="mechanical drawing"></p>

| Parameter | Value |
|---|---|
| Card size | M.2 Type 2242: 22.00 × 42.00 mm |
| PCB | 0.8 mm, 4-layer (SIG/GND/PWR/SIG), ENIG + bevelled gold fingers |
| Max height, top side | 4.2 mm (JST SH headers) · ≈6.3 mm with plug mated |
| Max height, bottom side | ≤1.5 mm (compliant with H4.2 socket B-side envelope) |
| Socket coverage zone | first 4.8 mm from card edge kept component-free (both faces) |
| Mounting | M.2 screw, Ø3.5 semicircular notch, plated GND pad |
| Component sides | SMT both sides (top: module + connectors; bottom: passives) |

## LEDs & test points

| Item | Location | Function |
|---|---|---|
| Green LED (D3) | side-view, left card edge | 3.3 V rail present |
| Red LED (D4) | side-view, left card edge | firmware status, active-low on IO48 |
| TP1/TP2 | bottom | EN / IO0 (recovery without host sidebands) |
| TP3/TP4 | bottom | UART0 TX / RX |
| TP5/TP6 | bottom | 3.3 V / GND |

The LEDs are side-view parts emitting out of the left card edge — visible
with the card in the slot regardless of mounting orientation. Test points
are on the bottom side (bench use).

## Host compatibility

| Host | Status |
|---|---|
| Toradex Verdin + Mallow (X17) | Primary — verified pin mapping, recovery documented |
| Any M.2 Key-B slot with USB 2.0 | Enumerates and flashes; recovery needs 2 host GPIOs (or TPs) |
| RPi 5 + Waveshare Key-B HAT | Nice-to-have (ADR 0004) — USB works, 2242 standoff & sidebands unverified |
| Enclosed hosts (laptops/WWAN bays) | **Not compatible** — height (R11) |

## Design data

Schematic PDF (`make sch`), interactive 3D, BOM (`make check`), layout and
all sources in this repository. License: CERN-OHL-P v2.
"""


if __name__ == "__main__":
    main()
