from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

design = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'M2_KEYB_2242_EDGE', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'M2_KEYB_2242_EDGE'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'esp32m2:M2_KeyB_2242_EdgeFingers', 'keywords':None, 'description':'M.2 Key-B 2242 card edge gold fingers (PCB feature)', 'datasheet':None, 'pins':[
            Pin(num='1',name='CONFIG_3',func=pin_types.NOCONNECT),
            Pin(num='2',name='VCC_3V3',func=pin_types.PWRIN),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='VCC_3V3',func=pin_types.PWRIN),
            Pin(num='5',name='GND',func=pin_types.PWRIN),
            Pin(num='6',name='FULL_CARD_POWER_OFF_n',func=pin_types.NOCONNECT),
            Pin(num='7',name='USBH3_D_P',func=pin_types.BIDIR),
            Pin(num='8',name='W_DISABLE1_n',func=pin_types.INPUT),
            Pin(num='9',name='USBH3_D_N',func=pin_types.BIDIR),
            Pin(num='10',name='WWAN_LED_n',func=pin_types.NOCONNECT),
            Pin(num='11',name='GND',func=pin_types.PWRIN),
            Pin(num='20',name='PCIE_1_GPIO_5',func=pin_types.INPUT),
            Pin(num='21',name='CONFIG_0',func=pin_types.NOCONNECT),
            Pin(num='22',name='PCIE_1_GPIO_6',func=pin_types.NOCONNECT),
            Pin(num='23',name='PCIE_1_GPIO_11',func=pin_types.NOCONNECT),
            Pin(num='24',name='PCIE_1_GPIO_7',func=pin_types.NOCONNECT),
            Pin(num='25',name='DPR',func=pin_types.NOCONNECT),
            Pin(num='26',name='PCIE_1_GPIO_10',func=pin_types.NOCONNECT),
            Pin(num='27',name='GND',func=pin_types.PWRIN),
            Pin(num='28',name='PCIE_1_GPIO_8',func=pin_types.NOCONNECT),
            Pin(num='29',name='USBH3_SSRX_N',func=pin_types.NOCONNECT),
            Pin(num='30',name='PCIE_1_UIM_RESET',func=pin_types.NOCONNECT),
            Pin(num='31',name='USBH3_SSRX_P',func=pin_types.NOCONNECT),
            Pin(num='32',name='PCIE_1_UIM_CLK',func=pin_types.NOCONNECT),
            Pin(num='33',name='GND',func=pin_types.PWRIN),
            Pin(num='34',name='PCIE_1_UIM_DATA',func=pin_types.NOCONNECT),
            Pin(num='35',name='USBH3_SSTX_N',func=pin_types.NOCONNECT),
            Pin(num='36',name='PCIE_1_UIM_PWR',func=pin_types.NOCONNECT),
            Pin(num='37',name='USBH3_SSTX_P',func=pin_types.NOCONNECT),
            Pin(num='38',name='SDX2AP_STATUS',func=pin_types.NOCONNECT),
            Pin(num='39',name='GND',func=pin_types.PWRIN),
            Pin(num='40',name='PCIE_1_GPIO_0',func=pin_types.NOCONNECT),
            Pin(num='41',name='PCIE_1_L0_RX_N',func=pin_types.NOCONNECT),
            Pin(num='42',name='PCIE_1_GPIO_1',func=pin_types.NOCONNECT),
            Pin(num='43',name='PCIE_1_L0_RX_P',func=pin_types.NOCONNECT),
            Pin(num='44',name='PCIE_1_GPIO_2',func=pin_types.NOCONNECT),
            Pin(num='45',name='GND',func=pin_types.PWRIN),
            Pin(num='46',name='PCIE_1_GPIO_3',func=pin_types.NOCONNECT),
            Pin(num='47',name='PCIE_1_L0_TX_N',func=pin_types.NOCONNECT),
            Pin(num='48',name='PCIE_1_GPIO_4',func=pin_types.NOCONNECT),
            Pin(num='49',name='PCIE_1_L0_TX_P',func=pin_types.NOCONNECT),
            Pin(num='50',name='PERST_n',func=pin_types.INPUT),
            Pin(num='51',name='GND',func=pin_types.PWRIN),
            Pin(num='52',name='PCIE_CLKREQ_n',func=pin_types.NOCONNECT),
            Pin(num='53',name='PCIE_1_CLK_N',func=pin_types.NOCONNECT),
            Pin(num='54',name='PCIE_1_WAKE_n',func=pin_types.NOCONNECT),
            Pin(num='55',name='PCIE_1_CLK_P',func=pin_types.NOCONNECT),
            Pin(num='56',name='RFFE_CLK',func=pin_types.NOCONNECT),
            Pin(num='57',name='GND',func=pin_types.PWRIN),
            Pin(num='58',name='RFFE_DATA',func=pin_types.NOCONNECT),
            Pin(num='59',name='LAA_TX_EN',func=pin_types.NOCONNECT),
            Pin(num='60',name='WLAN_TX_EN',func=pin_types.NOCONNECT),
            Pin(num='61',name='ANTCTL1',func=pin_types.NOCONNECT),
            Pin(num='62',name='COEX_RXD',func=pin_types.NOCONNECT),
            Pin(num='63',name='ANTCTL2',func=pin_types.NOCONNECT),
            Pin(num='64',name='COEX_TXD',func=pin_types.NOCONNECT),
            Pin(num='65',name='RFFE_VIO_1V8',func=pin_types.NOCONNECT),
            Pin(num='66',name='PCIE_1_UIM_CD',func=pin_types.NOCONNECT),
            Pin(num='67',name='M2_CARD_RESET_n',func=pin_types.NOCONNECT),
            Pin(num='68',name='AP2SDX_STATUS',func=pin_types.NOCONNECT),
            Pin(num='69',name='CONFIG_1',func=pin_types.NOCONNECT),
            Pin(num='70',name='VCC_3V3',func=pin_types.PWRIN),
            Pin(num='71',name='GND',func=pin_types.PWRIN),
            Pin(num='72',name='VCC_3V3',func=pin_types.PWRIN),
            Pin(num='73',name='GND',func=pin_types.PWRIN),
            Pin(num='74',name='VCC_3V3',func=pin_types.PWRIN),
            Pin(num='75',name='CONFIG_2',func=pin_types.NOCONNECT)] }),
        Part(**{ 'name':'FerriteBead', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'FerriteBead'}), 'ref_prefix':'FB', 'fplist':[''], 'footprint':'Inductor_SMD:L_0805_2012Metric', 'keywords':'L ferrite bead inductor filter', 'description':'Ferrite bead', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_SMD:C_0805_2012Metric', 'keywords':'cap capacitor', 'description':'Unpolarized capacitor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'USBLC6-2SC6', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USBLC6-2SC6'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-666', 'Package_TO_SOT_SMD:SOT-23-6'], 'footprint':'Package_TO_SOT_SMD:SOT-23-6', 'keywords':'usb ethernet video', 'description':'Very low capacitance ESD protection diode, 2 data-line, SOT-23-6', 'datasheet':'https://www.st.com/resource/en/datasheet/usblc6-2.pdf', 'pins':[
            Pin(num='1',name='I/O1',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='I/O2',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='I/O1',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='I/O2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':'R res resistor', 'description':'Resistor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'BAT54A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BAT54A'}), 'ref_prefix':'D', 'fplist':['Package_TO_SOT_SMD:SOT-23'], 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':'schottky diode', 'description':'schottky barrier diode', 'datasheet':'http://www.diodes.com/_files/datasheets/ds11005.pdf', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.NOCONNECT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'TestPoint', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TestPoint'}), 'ref_prefix':'TP', 'fplist':[''], 'footprint':'TestPoint:TestPoint_Pad_D1.5mm', 'keywords':'test point tp', 'description':'test point', 'datasheet':'~', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'ESP32-S3-WROOM-1', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ESP32-S3-WROOM-1'}), 'ref_prefix':'U', 'fplist':['RF_Module:ESP32-S3-WROOM-1'], 'footprint':'esp32m2:ESP32-S3-WROOM-1_JLC', 'keywords':'RF Radio BT ESP ESP32-S3 Espressif onboard PCB antenna', 'description':'RF Module, ESP32-S3 SoC, Wi-Fi 802.11b/g/n, Bluetooth, BLE, 32-bit, 3.3V, onboard antenna, SMD', 'datasheet':'https://www.espressif.com/sites/default/files/documentation/esp32-s3-wroom-1_wroom-1u_datasheet_en.pdf', 'pins':[
            Pin(num='3',name='EN',func=pin_types.INPUT,unit=1),
            Pin(num='27',name='IO0',func=pin_types.BIDIR,unit=1),
            Pin(num='39',name='IO1',func=pin_types.NOCONNECT,unit=1),
            Pin(num='38',name='IO2',func=pin_types.NOCONNECT,unit=1),
            Pin(num='15',name='IO3',func=pin_types.NOCONNECT,unit=1),
            Pin(num='4',name='IO4',func=pin_types.NOCONNECT,unit=1),
            Pin(num='5',name='IO5',func=pin_types.NOCONNECT,unit=1),
            Pin(num='6',name='IO6',func=pin_types.NOCONNECT,unit=1),
            Pin(num='7',name='IO7',func=pin_types.NOCONNECT,unit=1),
            Pin(num='12',name='IO8',func=pin_types.BIDIR,unit=1),
            Pin(num='17',name='IO9',func=pin_types.BIDIR,unit=1),
            Pin(num='18',name='IO10',func=pin_types.BIDIR,unit=1),
            Pin(num='19',name='IO11',func=pin_types.BIDIR,unit=1),
            Pin(num='20',name='IO12',func=pin_types.BIDIR,unit=1),
            Pin(num='21',name='IO13',func=pin_types.BIDIR,unit=1),
            Pin(num='22',name='IO14',func=pin_types.BIDIR,unit=1),
            Pin(num='8',name='IO15',func=pin_types.NOCONNECT,unit=1),
            Pin(num='9',name='IO16',func=pin_types.NOCONNECT,unit=1),
            Pin(num='2',name='3V3',func=pin_types.PWRIN,unit=1),
            Pin(num='1',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='40',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='41',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='37',name='TXD0',func=pin_types.BIDIR,unit=1),
            Pin(num='36',name='RXD0',func=pin_types.BIDIR,unit=1),
            Pin(num='10',name='IO17',func=pin_types.NOCONNECT,unit=1),
            Pin(num='11',name='IO18',func=pin_types.NOCONNECT,unit=1),
            Pin(num='13',name='USB_D-',func=pin_types.BIDIR,unit=1),
            Pin(num='14',name='USB_D+',func=pin_types.BIDIR,unit=1),
            Pin(num='23',name='IO21',func=pin_types.BIDIR,unit=1),
            Pin(num='28',name='IO35',func=pin_types.NOCONNECT,unit=1),
            Pin(num='29',name='IO36',func=pin_types.NOCONNECT,unit=1),
            Pin(num='30',name='IO37',func=pin_types.NOCONNECT,unit=1),
            Pin(num='31',name='IO38',func=pin_types.NOCONNECT,unit=1),
            Pin(num='32',name='IO39',func=pin_types.NOCONNECT,unit=1),
            Pin(num='33',name='IO40',func=pin_types.NOCONNECT,unit=1),
            Pin(num='34',name='IO41',func=pin_types.NOCONNECT,unit=1),
            Pin(num='35',name='IO42',func=pin_types.NOCONNECT,unit=1),
            Pin(num='26',name='IO45',func=pin_types.NOCONNECT,unit=1),
            Pin(num='16',name='IO46',func=pin_types.NOCONNECT,unit=1),
            Pin(num='24',name='IO47',func=pin_types.NOCONNECT,unit=1),
            Pin(num='25',name='IO48',func=pin_types.BIDIR,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'LED', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LED'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'LED_SMD:LED_0805_2012Metric', 'keywords':'LED diode', 'description':'Light emitting diode', 'datasheet':'~', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x12', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x12'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x12_P2.54mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x12, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'~', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='Pin_5',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='Pin_6',func=pin_types.PASSIVE,unit=1),
            Pin(num='7',name='Pin_7',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',name='Pin_8',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',name='Pin_9',func=pin_types.PASSIVE,unit=1),
            Pin(num='10',name='Pin_10',func=pin_types.PASSIVE,unit=1),
            Pin(num='11',name='Pin_11',func=pin_types.PASSIVE,unit=1),
            Pin(num='12',name='Pin_12',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] })])